### ISSUE TITLE
Bug: App crashesh after selecting an image

### ISSUE THREAD

**Issue by 991rajat** [CropAi/Android-Application#47]
**Description**
App Crashes after selecting an image.

**Log**
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=-1, data=Intent { dat=content://media/external/images/media/75376 flg=0x1 launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }} to activity {com.boss.cropanalyzerapp/com.boss.cropanalyzerapp.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4556)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4599)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6816)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at com.boss.cropanalyzerapp.MainActivity.onActivityResult(MainActivity.java:232)
        at android.app.Activity.dispatchActivityResult(Activity.java:7337)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4552)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4599) 
        at android.app.ActivityThread.-wrap22(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6816) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453) 

**Device**
Samsung J2 Android 7.1.1 API 25

**Comment by tanishq9** [comment]
Which API version is your android device ? Also, any workaround you know for this bug ?

**Comment by 991rajat** [comment]
Yeah I found out after commenting this Log.e(TAG, data.getData().getPath().split(":")[1]); it works.
Also when I install on different phone it worked without any worry.

**Comment by tanishq9** [comment]
Ok, we shall delete that log statement then. Thanks for pointing out.

**Comment by tanishq9** [comment]
Feel free to open another issue in case of any other bug. Closing this one.
